name: Build Multi-Platform Executables

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build executable with Makefile
      run: |
        make windows-amd64

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-tool-windows-amd64
        path: release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build executable with Makefile
      run: |
        make linux-amd64

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-tool-linux-amd64
        path: release/

  build-macos-intel:
    runs-on: macos-13  # Intel mac
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build executable with Makefile
      run: |
        make darwin-amd64

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-tool-darwin-amd64
        path: release/

  build-macos-arm:
    runs-on: macos-14  # Apple Silicon mac
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build executable with Makefile
      run: |
        make darwin-arm64

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qbittorrent-tool-darwin-arm64
        path: release/
