name: Build Multi-Platform Executables

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Install build dependencies
    #   run: |
    #     pip install pyinstaller

    - name: Build executable with Makefile
      run: |
        make windows-amd64

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        path: release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Install build dependencies
    #   run: |
    #     pip install pyinstaller

    - name: Build executable with Makefile
      run: |
        make linux-amd64

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        path: release/

  build-macos-intel:
    runs-on: macos-13  # Intel mac
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Install build dependencies
    #   run: |
    #     pip install pyinstaller

    - name: Build executable with Makefile
      run: |
        make darwin-amd64

    - name: Upload macOS Intel artifacts
      uses: actions/upload-artifact@v4
      with:
        path: release/

  build-macos-arm:
    runs-on: macos-14  # Apple Silicon mac
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Install build dependencies
    #   run: |
    #     pip install pyinstaller

    - name: Build executable with Makefile
      run: |
        make darwin-arm64

    - name: Upload macOS ARM artifacts
      uses: actions/upload-artifact@v4
      with:
        path: release/
